version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
      - h2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  h2:
    image: oscarfonts/h2
    ports:
      - "51521:1521"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -ifNotExists"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "56379:6379"
    restart: unless-stopped